version: '3'
services:
  neo4j:
    image: neo4j:4.4.7-community
    restart: unless-stopped
    ports:
      - 7575:7575
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_connector_https_advertised__address=:7574
      - NEO4J_dbms_connector_http_advertised__address=:7575
      - NEO4J_dbms_connector_http_listen__address=:7575
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4JLABS_PLUGINS=["apoc"]
