version: "3"
services:
  memgraph-platform:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - ./memgraph/lib:/var/lib/memgraph
      - ./memgraph/log:/var/log/memgraph
      - ./memgraph/etc:/etc/memgraph
      - ./import:/import
    env_file:
      - /memgraph/.env # Replace this with the actual path to your .env file
    entrypoint: ["/usr/bin/supervisord"]
