version: '3'
services:
  neo4j:
    image: neo4j:5.9.0-community
    restart: unless-stopped
    ports:
      - 7575:7575
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_http_advertised__address=:7574
      - NEO4J_server_https_advertised__address=:7575
      - NEO4J_server_http_listen__address=:7575
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_server_bolt_listen__address=:7687
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/etym1234 # CHANGE THIS IF YOU ARE EXPOSING OVER INTERNET
